package com.tripath.data.local.database.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One set within a [LiftSessionLog], synced read-only from `content://com.liftpath.share`.
 *
 * There is no LiftPath-side set id in the contract, so [id] is a local autogenerated key —
 * [com.tripath.data.local.liftpath.LiftPathSyncManager] always replaces every set belonging to a
 * session together, so this table never accumulates stale rows across a re-sync.
 */
@Entity(
    tableName = "lift_set_logs",
    foreignKeys = [
        ForeignKey(
            entity = LiftSessionLog::class,
            parentColumns = ["id"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("sessionId")]
)
data class LiftSetLog(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val sessionId: String,
    /** [LiftExerciseCatalogEntry.id] — the exercise catalog id, not this table's own key. */
    val exerciseId: Int,
    val setNumber: Int,
    val kg: Float,
    val reps: Int,
    val rpe: Float? = null,
    val isWarmup: Boolean = false,
    /** [com.liftpath.models.SetIntent] name, resolved on the LiftPath side. */
    val intent: String? = null,
    val durationSeconds: Int? = null,
    val bodyweightKg: Float? = null
)
