package com.tripath.domain.coach

/**
 * Color coding for readiness status visualization.
 */
enum class ReadinessColor {
    GREEN,  // Ready to train (>75 score)
    YELLOW, // Caution (40-75 score)
    RED     // Not ready (<40 score)
}

/**
 * Type of warning generated by the training rules engine.
 */
enum class WarningType {
    INJURY_RISK,      // Risk of injury detected
    RULE_VIOLATION,   // Training rule violated
    RECOVERY_ADVICE   // Recovery recommendation
}

/**
 * Training phase for the Iron Brain rules engine.
 * Separate from the existing TrainingPhase sealed class used for periodization.
 */
enum class TrainingPhase {
    OFF_SEASON,
    BASE,
    BUILD,
    PEAK,
    TAPER,
    RACING
}

/**
 * Readiness status calculated from multiple recovery metrics.
 * 
 * @param score Overall readiness score (0-100)
 * @param color Color coding for quick visualization
 * @param breakdown Human-readable breakdown of component scores
 * @param allergyPenalty Penalty points applied due to allergy severity
 */
data class ReadinessStatus(
    val score: Int, // 0-100
    val color: ReadinessColor,
    val breakdown: String, // e.g. "TSB: 40, Sleep: 20, Subjective: 30"
    val allergyPenalty: Int
)

/**
 * Warning generated by the training rules engine.
 * 
 * @param type Category of warning
 * @param title Short title for the warning
 * @param message Detailed message explaining the warning
 * @param isBlocker If true, this is a hard rule violation that should block the plan
 */
data class CoachWarning(
    val type: WarningType,
    val title: String,
    val message: String,
    val isBlocker: Boolean = false // If true, violates a hard rule
)

/**
 * Structural Stress Score representing mechanical load from running.
 * 
 * @param value Calculated SSS value
 * @param isHighRisk If true, indicates high risk of injury from mechanical load
 */
data class StructuralStressScore(
    val value: Double,
    val isHighRisk: Boolean
)


